# Generated by Django 3.2.4 on 2021-06-25 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStampModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128)),
                ('name', models.CharField(max_length=10)),
                ('nickname', models.CharField(max_length=20)),
                ('point', models.IntegerField(default=0)),
                ('level', models.CharField(default=0, max_length=10)),
                ('password', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service_upload',
            fields=[
                ('timestampmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='myapp.timestampmodel')),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('service', models.TextField()),
                ('evalu1', models.IntegerField(choices=[(1, 'commercial'), (2, 'public interest'), (3, 'creativity')])),
                ('evalu2', models.IntegerField(choices=[(1, 'commercial'), (2, 'public interest'), (3, 'creativity')])),
                ('evalu3', models.IntegerField(choices=[(1, 'commercial'), (2, 'public interest'), (3, 'creativity')])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.user', verbose_name='작성자')),
            ],
            bases=('myapp.timestampmodel',),
        ),
    ]
