# Generated by Django 3.2.5 on 2021-07-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_upload',
            name='evalu1',
            field=models.IntegerField(choices=[(1, '상업성'), (2, '공익성'), (3, '창의성'), (4, '발전가능성'), (5, '디자인'), (6, '편의성')]),
        ),
        migrations.AlterField(
            model_name='service_upload',
            name='evalu2',
            field=models.IntegerField(choices=[(1, '상업성'), (2, '공익성'), (3, '창의성'), (4, '발전가능성'), (5, '디자인'), (6, '편의성')]),
        ),
        migrations.AlterField(
            model_name='service_upload',
            name='evalu3',
            field=models.IntegerField(choices=[(1, '상업성'), (2, '공익성'), (3, '창의성'), (4, '발전가능성'), (5, '디자인'), (6, '편의성')]),
        ),
    ]
