# Generated by Django 3.2.4 on 2021-06-27 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_evalu_comment',
            name='service_evalu_upload_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='myapp.service_evalu_upload', verbose_name='Service_upload'),
        ),
    ]
