# Generated by Django 3.2.5 on 2021-07-03 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210702_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_evalu_upload',
            name='title',
        ),
    ]
