# Generated by Django 3.2.5 on 2021-07-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_service_evalu_upload_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_upload',
            name='grade1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service_upload',
            name='grade2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service_upload',
            name='grade3',
            field=models.IntegerField(default=0),
        ),
    ]
